### PR TITLE
add termination_grace_period_seconds advanced setting

### PR DESCRIPTION
**Pull request by kwigley**
just wanted to get my hands on the engine codebase, please close if not accepting contributions

### CODE REVIEW

**Comment by benjaminch** [comment]
Hello @kwigley,

Thanks a lot for this nice contribution :)

This is definitively something we want to integrate into the Engine.
In order to proceed, we will need just a bit of time mainly for the following reasons:

1. This repo is a mirror, so we need to cherry-pick your commit and apply it to the root repo
2. We need to add the "plumbing" work to integrate this feature into our product (API + frontend)

I am adding this to our internal backlog :)

Thanks again for your contribution, very much appreciated !

**Comment by kwigley** [comment]
sounds good @benjaminch! thank you 👍

**Comment by deimosfr** [comment]
Sorry for the delay and thanks for the PR. It will be merged in the coming days

**Comment by acarranoqovery** [comment]
Hi @kwigley , this has been released. thanks for your PR!  https://hub.qovery.com/docs/using-qovery/configuration/advanced-settings/#deploymenttermination_grace_period_seconds

**Pull request closed without merging**
